---
- name: Update des paquets
  apt:
    update_cache: yes
  when: ansible_facts['os_family'] == 'Ubuntu'

- name: Installation des paquets (Ubuntu)
  apt:
    name:
      - apache2
      - php
      - libapache2-mod-php
      - php-mysql
      - mariadb-server
      - wget
      - unzip
    state: present
  when: ansible_facts['os_family'] == 'Ubuntu'

- name: Installation des paquets (Rocky)
  dnf:
    name:
      - httpd
      - php
      - mariadb-server
      - wget
      - unzip
    state: present
  when: ansible_facts['os_family'] == 'Rocky'

- name: Suppression de la page par défaut
  file:
    path: /var/www/html/index.html
    state: absent

- name: Demarrage de Apache (Ubuntu)
  service:
    name: apache2
    state: restarted
  when: ansible_facts['os_family'] == 'Ubuntu'

- name: Demarrage de Apache (Rocky)
  command: /usr/sbin/httpd -DFOREGROUND
  when: ansible_facts['os_family'] == 'Rocky'

- name: Demarrage de MariaDB
  command: mysqld_safe --datadir=/var/lib/mysql &
  async: 0
  poll: 0

- name: Securisation de MariaDB
  mysql_db:
    name: "{{ wordpress_db_name }}"
    state: present
    login_user: root
    login_password: "{{ mariadb_root_password }}"
    encoding: utf8mb4

- name: Configuration de la base de donnees WordPress
  mysql_user:
    name: "{{ wordpress_db_user }}"
    password: "{{ wordpress_db_password }}"
    priv: "{{ wordpress_db_name }}.*:ALL"
    state: present
    login_user: root
    login_password: "{{ mariadb_root_password }}"

- name: Telechargement et extraction de WordPress
  unarchive:
    src: https://wordpress.org/latest.zip
    dest: /tmp
    remote_src: yes

- name: Copie de WordPress dans le repertoire web
  copy:
    src: "/tmp/wordpress/*"
    dest: /var/www/html/
    owner: "{{ apache_user }}"
    group: "{{ apache_group }}"
    mode: '0755'
    recurse: yes

- name: Création du fichier wp-config.php
  template:
    src: wp-config.php.j2
    dest: /var/www/html/wp-config.php
    owner: "{{ apache_user }}"
    group: "{{ apache_group }}"
    mode: '0640'

- name: Configuration Apache pour WordPress
  template:
    src: wordpress.conf.j2
    dest: /etc/apache2/sites-available/wordpress.conf
  notify: Reload Apache

- name: Activation du site WordPress (Ubuntu)
  apache2_site:
    name: wordpress.conf
    state: enabled
  when: ansible_facts['os_family'] == 'Ubuntu'

- name: Activation du site WordPress (Rocky)
  command: /usr/sbin/httpd -DFOREGROUND
  when: ansible_facts['os_family'] == 'Rocky'

- name: Rechargement de la configuration Apache
  service:
    name: apache2
    state: reloaded
  when: ansible_facts['os_family'] == 'Ubuntu'

