---
- name: Installer et configurer WordPress
  hosts: all
  become: yes
  tasks:

    # Installer les paquets requis (Ubuntu ou Rocky)
    - name: Installer les paquets requis
      package:
        name: "{{ item }}"
        state: present
      loop: "{{ wordpress_packages[ansible_os_family] }}"

    # Activer et démarrer Apache et MariaDB en fonction de l'OS
    - name: Activer et démarrer Apache et MariaDB
      service:
        name: "{{ item }}"
        state: started
        enabled: true
      loop: "{{ wordpress_services[ansible_os_family] }}"

    # Créer le répertoire web root si absent
    - name: Créer le répertoire web root si absent
      file:
        path: "{{ wordpress_web_root }}"
        state: directory
        owner: www-data
        group: www-data
        mode: '0755'

    # Télécharger WordPress
    - name: Télécharger WordPress
      get_url:
        url: "{{ wordpress_url }}"
        dest: /tmp/latest.zip

    # Extraire WordPress
    - name: Extraire WordPress
      unarchive:
        src: /tmp/latest.zip
        dest: /tmp/
        remote_src: yes

    # Copier les fichiers WordPress
    - name: Copier les fichiers WordPress
      copy:
        src: /tmp/wordpress/
        dest: "{{ wordpress_web_root }}/"
        owner: www-data
        group: www-data
        mode: '0755'
        remote_src: yes

    # Supprimer la page par défaut d’Apache
    - name: Supprimer la page par défaut d’Apache
      file:
        path: "{{ wordpress_web_root }}/index.html"
        state: absent

    # Notifier de redémarrer le serveur web après copie de WordPress
    - name: Redémarrer le serveur web
      service:
        name: "{{ apache_service }}"
        state: restarted
      notify: Restart Apache

  vars:
    wordpress_url: "https://wordpress.org/latest.tar.gz"
    wordpress_web_root: "/var/www/html"
    wordpress_packages:
      Debian:  # Pour Ubuntu
        - apache2
        - mariadb-server
        - php
        - php-mysql
        - libapache2-mod-php
        - unzip
      RedHat:  # Pour Rocky Linux
        - httpd
        - mariadb-server
        - php
        - php-mysqlnd
        - mod_php
        - unzip

    wordpress_services:
      Debian:  # Pour Ubuntu
        - apache2
        - mariadb
      RedHat:  # Pour Rocky Linux
        - httpd
        - mariadb

    apache_service: "{{ 'apache2' if ansible_os_family == 'Debian' else 'httpd' }}"
